services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=candidateDb'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgre'
    ports:
      - "5433:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
